language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  # - nightly
env:
  matrix:
    - CC="gcc"
    - CC="clang"
notifications:
  email: false
sudo: false # use a docker worker
addons:
  apt_packages:
  - libgmp-dev

# This replaces the `git fetch --unshallow` in the default Julia Travis script
git:
  depth: 99999999

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("GLPK"); Pkg.test("GLPK")'

after_success:
  - julia --check-bounds=yes --inline=no -e 'cd(Pkg.dir("GLPK")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
branches:
  except:
    - release-0.1
